### PR TITLE
Add ARM support (without NEON for now)

### PR DESCRIPTION
**Pull request by iver56**

### CODE REVIEW

**Review by magnus-nomono — CHANGES_REQUESTED** [review]
I would prefer if the x86 specific functions were grouped more together, this makes the code cleaner as you don't have to have as many if clauses. It also will be neater for when we add other platform intrinsics in the future

**Comment by iver56** [comment]
Could you make a suggestion of how it should be grouped together? Do we want to split it into different files?

**Comment by iver56** [comment]
What do you think of the way it is organized in https://github.com/nomonosound/numpy-rms/blob/main/numpy_rms/_rms.c?

**Comment by magnus-nomono** [comment]
> What do you think of the way it is organized in https://github.com/nomonosound/numpy-rms/blob/main/numpy_rms/_rms.c?

I think it's good. It is less code though. 

I think it is okay to have it in the same file for now, as long as it is kept more together, but we probably want to split it out in separate files when we add neon

**Review by magnus-nomono — APPROVED** [review]

**Pull request merged**
