### PR TITLE
Use msvc-compatible cpuid instruction. Switch from gcc to clang on Linux because perf.

### PR DESCRIPTION
**Pull request by iver56**
The joys of compiler differences 🤓 

Close https://github.com/nomonosound/numpy-minmax/issues/22

### CODE REVIEW

**Review by magnus-nomono — APPROVED** [review]
Looks OK, is there a reason why you added MSVC support? I got the impression we were not going to bother with it

**Comment by iver56** [comment]
> is there a reason why you added MSVC support?

cibuildwheel uses it for the windows builds

**Comment by magnus-nomono** [comment]
> > is there a reason why you added MSVC support?
> 
> cibuildwheel uses it for the windows builds

Does it automatically translate our build options too?

**Comment by iver56** [comment]
I think it just passes all the build options, and then msvc ignores the ones it doesn't understand

**Comment by magnus-nomono** [comment]
> I think it just passes all the build options, and then msvc ignores the ones it doesn't understand

Are you sure? Neither `mavx`, `mavx512f` nor `O3` are valid msvc build options. Have we tested the windows wheel built through the CI?

**Comment by magnus-nomono** [comment]
I was thinking more if it is compiled with proper optimizations

**Comment by iver56** [comment]
I have checked that the AVX optimization works on my laptop, but I have not checked AVX512, as my laptop does not support that

**Pull request merged**
